=== AppStateESS/canopy/mod/pagesmith/inc/page.dtd
<!ELEMENT template (title, summary, thumbnail, style, structure, folders?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT thumbnail (#PCDATA)>
<!ELEMENT style (#PCDATA)>
<!ELEMENT structure (section+)>
<!ELEMENT folders (name+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT section (name, type, width?, height?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>

=== AppStateESS/canopy/mod/pagesmith/templates/page_templates/document/structure.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "../../../inc/page.dtd">
<template>
    <title>Document</title>
    <summary>A large text area with an extended document area at the
        bottom.</summary>
    <thumbnail>document.png</thumbnail>
    <style>page.css</style>
    <structure>
        <section>
            <name>text1</name>
            <type>text</type>
        </section>
        <section>
            <name>document1</name>
            <type>document</type>
        </section>
    </structure>
    <folders>
        <name>one-column</name>
        <name>no-image</name>
    </folders>
</template>

=== AppStateESS/canopy/mod/pagesmith/templates/page_templates/banner/structure.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "../../../inc/page.dtd">

<template>
    <title>Banner</title>
    <summary>Wide banner image above text area.</summary>
    <thumbnail>banner.png</thumbnail>
    <style>page.css</style>
    <structure>
        <section>
            <name>text1</name>
            <type>text</type>
        </section>
        <section>
            <name>image1</name>
            <type>image</type>
            <width>700</width>
            <height>200</height>
        </section>
    </structure>
    <folders>
        <name>one-column</name>
        <name>one-image</name>
    </folders>
</template>

=== AppStateESS/canopy/mod/pagesmith/templates/page_templates/text_only/structure.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "../../../inc/page.dtd">
<template>
    <title>Text Only</title>
    <summary>One large text area and nothing else.</summary>
    <thumbnail>text_only.png</thumbnail>
    <style>page.css</style>
    <structure>
        <section>
            <name>text1</name>
            <type>text</type>
        </section>
    </structure>
    <folders>
        <name>one-column</name>
        <name>no-image</name>
    </folders>
</template>
